networks:
  zeconet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

services:
  postgres:
    image: postgres:14.3
    container_name: zefpg
    restart: always
    networks:
      zeconet:
        ipv4_address: 10.5.0.5 
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: fez
      POSTGRES_USER: zef
      POSTGRES_DB: zef
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - 'zef-db:/var/lib/postgresql/data'

  zeco:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zeco
    restart: always
    networks: ["zeconet"]
    depends_on: ["postgres"]
    working_dir: /app
    ports:
      - "9000:9000"
    environment:
      FEZ_ECO_CONFIG: "/app/resources/test-fez-eco-config.toml"
      FEZ_CONFIG: "/app/resources/test-fez-config.json"
    volumes:
      - ./:/app

volumes:
  zef-db:
