db='postgres://zef:fez@10.5.0.5:5432/zef'
dist-dl-uri='http://localhost:9000/not-here'
eco-prefix='fez'
delete-window=24
port=9000
email-command=[
  'raku',
  '-I.',
  '-MZeco::Util::Json',
  '-e',
  '$*TMPDIR.add("emailx").IO.spurt: to-j({to => @*ARGS[0], type => @*ARGS[1], related-id => @*ARGS[2] });',
]
dist-move-command=['raku', '-I.', '-MZeco::Util::Json', '-e', '$*TMPDIR.add("distx").IO.spurt: to-j({ src => @*ARGS[0], dest => @*ARGS[1] });']
